version: '3'
services:
  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    networks:
      - app-network
    volumes:
      - ./:/var/www/html
      - ./etc/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    depends_on:
      - php
  php:
    build: ./etc/infrastructure/php
    ports:
      - '9000:9000'
    networks:
      - app-network
    volumes:
      - ./:/var/www/html
      - ./etc/infrastructure/php/php.ini:/etc/php/8.1/fpm/conf.d/90-php.ini
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  my-db: